# Generated by Django 3.1.4 on 2021-01-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
