# Generated by Django 3.1.4 on 2021-01-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210107_1541'),
        ('Products', '0002_auto_20210107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shops', related_query_name='Shops', to='Accounts.shop', verbose_name='Shops'),
        ),
    ]
