# Generated by Django 3.1.4 on 2021-02-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210201_0309'),
        ('Products', '0004_auto_20210201_0309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('shop', 'product')},
        ),
    ]
