# Generated by Django 3.1.4 on 2021-02-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210201_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seen',
            field=models.IntegerField(default=0, verbose_name='seen'),
        ),
    ]
