# Generated by Django 3.1.4 on 2021-02-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210201_0309'),
        ('Products', '0006_product_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='shop', to='Accounts.Shop'),
        ),
    ]
