# Generated by Django 3.1.4 on 2021-02-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
