# Generated by Django 3.1.4 on 2021-02-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', related_query_name='comment_likes', to='Products.comment', verbose_name='comment'),
            preserve_default=False,
        ),
    ]
