# Generated by Django 3.1.4 on 2021-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_like_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create_at',
            field=models.TimeField(auto_now_add=True, default=0, verbose_name='create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='update_at',
            field=models.TimeField(auto_now=True, verbose_name='update at'),
        ),
    ]
