# Generated by Django 3.1.4 on 2021-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20210206_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='condition',
            field=models.BooleanField(verbose_name='condition'),
        ),
    ]
